version: "3.9"
services:
  crawl_influxdb:
    build: .
  influxdb:
    image: influxdb:1.8.3
    restart: always
    container_name: influxdb
    environment:
        - INFLUXDB_ADMIN_USER_PASSWORD=root
        - INFLUXDB_HTTP_AUTH_ENABLED=false
        - INFLUXDB_DB=temperature
    ports:
        - "8084:8083"
        - "8087:8086"
        - "8091:8090"
    volumes:
        - influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana:7.3.6
    container_name: grafana
    ports:
        - "3001:3000"
    depends_on:
        - influxdb
    volumes:
        - grafana:/var/lib/grafana
volumes:
    influxdb:
    grafana:
